services:
  postgres:
    image: postgres
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: axmayn
      POSTGRES_PASSWORD: password
      PG_DATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  customer-api:
    image: axmayn/customer-api:latest
    container_name: customer-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customer
    ports:
      - "8088:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - db



networks:
  db:
    driver: bridge

volumes:
  db: