spring:
  main:
    web-application-type : servlet

  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: axmayn
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/db/changelog/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show_sql: false



server:
  port : 8080
  error:
    include-stacktrace: never
    include-message: always

logging:
  level:
    liquibase: INFO