name: CI BUILD BACKEND
on:
  pull_request:
    branches:
      - main
    paths:
      - Backend/**

jobs:
  # Label of the container job
  build:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Service containers to run with `build-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:16.1
        # Provide the password for postgres
        env:
          POSTGRES_USER: axmayn
          POSTGRES_PASSWORD: password
          POSTGRES_DB: customer
        ports:
          - 5432:5432

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    defaults:
      run:
        working-directory: ./Backend
    steps:
      # Downloads a copy of the code in your repository before running CI tests and setup java
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'

        name: build and run unit/it test with maven
        run: mvn -ntp -B verify